apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: microservice
build:
  artifacts:
  - image: src-api
    context: backend
    docker:
        dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.cs'
          dest: .
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml