apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: microservice
build:
  artifacts:
  - image: src-api
    context: backend
    docker:
        dockerfile: Dockerfile
    sync:
      manual:
        - src: 'backend/**/*.cs'
          dest: .
  # - image: src-frontend
  #   context: frontend
  #   docker:
  #       dockerfile: Dockerfile
  #   sync:
  #     manual:
  #       - src: 'frontend/**/*.js'
  #         dest: .

profiles:
  - name: substring
    build:
      local:
        push: true
    deploy:
      kubectl:
        manifests:
          - k8s/staging/*.yaml

deploy:
  kubectl:
    manifests:
    - k8s/local/*.yaml
