apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-ingress
spec:
  rules:
    - host: mydomain.tld
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: src-api
                port: 
                  number: 80