import Head from "next/head";
import {
  Alert,
  AlertIcon,
  Button,
  Container,
  FormControl,
  FormLabel,
  Input,
  Radio,
  RadioGroup,
  Stack,
  Textarea,
} from "@chakra-ui/react";
import Intro from "../components/Frontend/intro";
import React, { useState } from "react";
import Layout from "../components/Frontend/layout";
import { Box } from "@chakra-ui/layout";

export default function Contact() {
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(false);
  const [success, setSuccess] = useState(false);

  const contact = (e) => {
    e.preventDefault();
    setError(false);
    setSubmitting(true);

    setTimeout(() => {
      setSuccess(true);
      setSubmitting(false);
    }, 3000);
  };

  return (
    <Layout>
      <Head>
        <title>Contact - billable</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro
        page={{
          title: "Contact",
          subtitle:
            "Do you have any questions about our service? Write us a message and we will happily help.",
        }}
      />
      <Container variant="SMALL">
        <Box as={"form"} onSubmit={contact}>
          {!success && (
            <Stack direction="column" spacing={8} pt={8} pb={16}>
              <FormControl id="Name">
                <FormLabel>Subject</FormLabel>
                <RadioGroup>
                  <Stack>
                    <Radio colorScheme="indigo" value="new-client">
                      I am interested in freqie
                    </Radio>
                    <Radio colorScheme="indigo" value="existing-client">
                      I am already a client
                    </Radio>
                    <Radio colorScheme="indigo" value="other">
                      Other
                    </Radio>
                  </Stack>
                </RadioGroup>
              </FormControl>
              <Stack spacing={8} direction={{ base: "column", lg: "row" }}>
                <FormControl id="Name">
                  <FormLabel>Name</FormLabel>
                  <Input
                    id="name"
                    name="name"
                    type="text"
                    autoComplete="name"
                    required
                  />
                </FormControl>
                <FormControl id="email">
                  <FormLabel>Email</FormLabel>
                  <Input
                    id="email"
                    name="email"
                    type="email"
                    autoComplete="email"
                    required
                  />
                </FormControl>
              </Stack>

              <FormControl id="Message">
                <FormLabel>Message</FormLabel>
                <Textarea isRequired rows={8} />
              </FormControl>
              <FormControl id="Message">
                <Button
                  colorScheme="indigo"
                  type="submit"
                  isLoading={submitting}
                  loadingText="Submitting"
                >
                  Submit
                </Button>
              </FormControl>
            </Stack>
          )}
          {error && (
            <Alert status="error" mt={3}>
              <AlertIcon />
              There was an error processing your request
            </Alert>
          )}
          {success && (
            <Alert status="success" mt={3}>
              <AlertIcon />
              We have received your message and will be in contact as soon as
              possible.
            </Alert>
          )}
        </Box>
      </Container>
    </Layout>
  );
}
