import Head from "next/head";
import Intro from "../components/Frontend/intro";
import React from "react";
import Layout from "../components/Frontend/layout";
import PricingSection from "../components/Frontend/sections/pricing";

export default function Pricing() {
  return (
    <Layout>
      <Head>
        <title>Contact - billable</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro
        page={{
          title: "Pricing",
          subtitle:
            "We offer different plans for your business needs. You can always upgrade or downgrade a plan.",
        }}
      />
      <PricingSection />
    </Layout>
  );
}
