import Head from "next/head";
import {
  Button,
  Container,
  FormControl,
  FormLabel,
  Input,
  Stack,
  Textarea,
} from "@chakra-ui/react";
import Intro from "../components/Frontend/intro";
import React from "react";
import Layout from "../components/Frontend/layout";

export default function PrivacyPolicy() {
  return (
    <Layout>
      <Head>
        <title>Contact - billable</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro
        page={{
          title: "Privacy Policy",
          subtitle:
            "Here you can find how we use your data to provide our service.",
        }}
      />
      <Container variant="SMALL"></Container>
    </Layout>
  );
}
