apiVersion: v1
kind: Service
metadata:
  name: src-frontend
  labels:
    app: src-frontend
spec:
  selector:
    app: src-frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-frontend
  labels:
    app: src-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: src-frontend
  template:
    metadata:
      labels:
        app: src-frontend
    spec:
      imagePullSecrets:
        - name: substringgmbh-docker-registry
      containers:
      - name: src-frontend
        image: src-frontend
        ports:
          - containerPort: 3000   
        env:
          - name: "ROOT_URL"
            value: "https://hackathon-api.substring.dev"           